# This file was generated by the {rix} R package v0.6.0 on 2024-03-22
# with following call:
# >rix(r_ver = "7872526e9c5332274ea5932a0c3270d6e4724f3b",
#  > r_pkgs = c("data_table"),
#  > overwrite = FALSE)
# It uses nixpkgs' revision 7872526e9c5332274ea5932a0c3270d6e4724f3b for reproducibility purposes
# which will install R version latest
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/NixOS/nixpkgs/archive/7872526e9c5332274ea5932a0c3270d6e4724f3b.tar.gz") {};
 rpkgs = builtins.attrValues {
  inherit (pkgs.rPackages) data_table;
};
   system_packages = builtins.attrValues {
  inherit (pkgs) R glibcLocales nix ;
};
  in
  pkgs.mkShell {
    LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
    LANG = "en_US.UTF-8";
    LC_ALL = "en_US.UTF-8";
    LC_TIME = "en_US.UTF-8";
    LC_MONETARY = "en_US.UTF-8";
    LC_PAPER = "en_US.UTF-8";
    LC_MEASUREMENT = "en_US.UTF-8";

    buildInputs = [  rpkgs  system_packages  ];
      
  }
